version: '3'
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'crudnodejsmysql'
      MYSQL_USER: 'crud'
      MYSQL_PASSWORD: 'abcd1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
